### ISSUE TITLE
Any reason libduo can't be a shared library?

### ISSUE THREAD

**Issue by z-tb** [duosecurity/libduo#5]
I'm working on incorporating libduo into an OpenLDAP module to initiate Duo push at the LDAP server. So far, I've only been able to get this setup working if libduo is built as a shared library (libduo.so). Is there a specific reason why using a shared lib might be a bad idea?  I'm assuming the decision to make libduo a static compile would be to eliminate shared library hacking but just a guess.

**Comment by xdesai** [comment]
Hi @z-tb!
You are correct that shared libraries do introduce some potential risks that don't exist for static libraries, but we believe that doesn't mean using shared libraries is inherently insecure. If you have the proper controls in place to protect your usage then it is probably fine. We won't be updating our Makefiles in the repo to make the change, but we won't discourage you from making that edit yourself in order to satisfy your use case.
Hope that helps!
-Xander

**Comment by z-tb** [comment]
Ok, Thank you for the info.

**Comment by xdesai** [comment]
Gonna close out this issue. Let me know if you have any more questions!
